

vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/error_adapter/error_adapter_0003.sv"                                                 -work error_adapter_0                                           
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_router/altera_merlin_router_0005.sv"                                   -work router                                                    
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_multiplexer/altera_merlin_multiplexer_0004.sv"                         -work rsp_mux                                                   
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_multiplexer/altera_merlin_arbitrator.sv"                               -work rsp_mux                                                   
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_demultiplexer/altera_merlin_demultiplexer_0004.sv"                     -work rsp_demux                                                 
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_multiplexer/altera_merlin_multiplexer_0003.sv"                         -work cmd_mux                                                   
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_multiplexer/altera_merlin_arbitrator.sv"                               -work cmd_mux                                                   
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_demultiplexer/altera_merlin_demultiplexer_0003.sv"                     -work cmd_demux                                                 
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_router/altera_merlin_router_0004.sv"                                   -work router_001                                                
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_router/altera_merlin_router_0003.sv"                                   -work router                                                    
vlogan +v2k           "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_st_adapter/altera_avalon_st_adapter_0001.v"                            -work avalon_st_adapter                                         
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_st_handshake_clock_crosser/altera_avalon_st_handshake_clock_crosser.v" -work crosser                                                   
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_st_handshake_clock_crosser/altera_avalon_st_clock_crosser.v"           -work crosser                                                   
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_st_handshake_clock_crosser/altera_avalon_st_pipeline_base.v"           -work crosser                                                   
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_st_handshake_clock_crosser/altera_std_synchronizer_nocut.v"            -work crosser                                                   
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_multiplexer/altera_merlin_multiplexer_0002.sv"                         -work rsp_mux                                                   
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_multiplexer/altera_merlin_arbitrator.sv"                               -work rsp_mux                                                   
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_demultiplexer/altera_merlin_demultiplexer_0002.sv"                     -work rsp_demux                                                 
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_multiplexer/altera_merlin_multiplexer_0001.sv"                         -work cmd_mux                                                   
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_multiplexer/altera_merlin_arbitrator.sv"                               -work cmd_mux                                                   
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_demultiplexer/altera_merlin_demultiplexer_0001.sv"                     -work cmd_demux                                                 
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_traffic_limiter/altera_merlin_traffic_limiter.sv"                      -work merlin_master_translator_avalon_universal_master_0_limiter
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_traffic_limiter/altera_merlin_reorder_memory.sv"                       -work merlin_master_translator_avalon_universal_master_0_limiter
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_traffic_limiter/altera_avalon_sc_fifo.v"                               -work merlin_master_translator_avalon_universal_master_0_limiter
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_traffic_limiter/altera_avalon_st_pipeline_base.v"                      -work merlin_master_translator_avalon_universal_master_0_limiter
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_router/altera_merlin_router_0002.sv"                                   -work router_001                                                
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_router/altera_merlin_router_0001.sv"                                   -work router                                                    
vlogan +v2k           "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_sc_fifo/altera_avalon_sc_fifo.v"                                       -work tx_bridge_s0_agent_rsp_fifo                               
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_slave_agent/altera_merlin_slave_agent.sv"                              -work tx_bridge_s0_agent                                        
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_slave_agent/altera_merlin_burst_uncompressor.sv"                       -work tx_bridge_s0_agent                                        
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_master_agent/altera_merlin_master_agent.sv"                            -work merlin_master_translator_avalon_universal_master_0_agent  
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_slave_translator/altera_merlin_slave_translator.sv"                    -work tx_bridge_s0_translator                                   
vlogan +v2k           "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_reset_controller/altera_reset_controller.v"                                   -work rst_controller                                            
vlogan +v2k           "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_reset_controller/altera_reset_synchronizer.v"                                 -work rst_controller                                            
vlogan +v2k           "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_mm_interconnect/altera_mm_interconnect_0003.v"                                -work mm_interconnect_2                                         
vlogan +v2k           "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_mm_interconnect/altera_mm_interconnect_0002.v"                                -work mm_interconnect_1                                         
vlogan +v2k           "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_mm_interconnect/altera_mm_interconnect_0001.v"                                -work mm_interconnect_0                                         
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/timing_adapter/timing_adapter_0008.sv"                                               -work rxtx_timing_adapter_pauselen_tx                           
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/timing_adapter/timing_adapter_0007.sv"                                               -work rxtx_timing_adapter_pauselen_rx                           
vlogan +v2k           "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_dc_fifo/altera_avalon_dc_fifo.v"                                       -work rxtx_dc_fifo_link_fault_status                            
vlogan +v2k           "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_dc_fifo/altera_dcfifo_synchronizer_bundle.v"                           -work rxtx_dc_fifo_link_fault_status                            
vlogan +v2k           "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_dc_fifo/altera_std_synchronizer_nocut.v"                               -work rxtx_dc_fifo_link_fault_status                            
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/timing_adapter/timing_adapter_0006.sv"                                               -work txrx_timing_adapter_link_fault_status_export              
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/timing_adapter/timing_adapter_0005.sv"                                               -work txrx_timing_adapter_link_fault_status_rx                  
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/error_adapter/error_adapter_0002.sv"                                                 -work rx_st_error_adapter_stat                                  
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_st_delay/altera_avalon_st_delay.sv"                                    -work rx_st_status_output_delay                                 
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_eth_crc_pad_rem/altera_eth_crc_pad_rem_pipeline_stage.sv"                     -work rx_eth_crc_pad_rem                                        
vlogan +v2k           "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_eth_crc_pad_rem/altera_eth_crc_pad_rem_pipeline_base.v"                       -work rx_eth_crc_pad_rem                                        
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/timing_adapter/timing_adapter_0004.sv"                                               -work rx_timing_adapter_frame_status_out_frame_decoder          
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_eth_frame_decoder/altera_eth_frame_decoder_pipeline_stage.sv"                 -work rx_eth_frame_decoder                                      
vlogan +v2k           "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_eth_frame_decoder/altera_eth_frame_decoder_pipeline_base.v"                   -work rx_eth_frame_decoder                                      
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/timing_adapter/timing_adapter_0003.sv"                                               -work rx_st_timing_adapter_frame_status_in                      
vlogan +v2k           "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_eth_10g_rx_register_map/altera_avalon_st_clock_crosser.v"                     -work rx_register_map                                           
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/timing_adapter/timing_adapter_0002.sv"                                               -work tx_st_timing_adapter_splitter_out_0                       
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_st_splitter/altera_avalon_st_splitter.sv"                              -work tx_st_splitter_xgmii                                      
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/timing_adapter/timing_adapter_0001.sv"                                               -work tx_st_timing_adapter_splitter_in                          
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_st_pipeline_stage/altera_avalon_st_pipeline_stage.sv"                  -work tx_st_pipeline_stage_rs                                   
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_st_pipeline_stage/altera_avalon_st_pipeline_base.v"                    -work tx_st_pipeline_stage_rs                                   
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/multiplexer/multiplexer_0001.sv"                                                     -work tx_st_mux_flow_control_user_frame                         
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/error_adapter/error_adapter_0001.sv"                                                 -work tx_st_pause_ctrl_error_adapter                            
vlogan +v2k           "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_eth_10g_tx_register_map/altera_avalon_st_clock_crosser.v"                     -work tx_register_map                                           
vlogan +v2k           "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_mm_bridge/altera_avalon_mm_bridge.v"                                   -work tx_bridge                                                 
vlogan +v2k -sverilog "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_master_translator/altera_merlin_master_translator.sv"                  -work merlin_master_translator                                  
vlogan +v2k           "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/Eth_10gmac.v"                                                                                                                                        
