

ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/error_adapter/error_adapter_0003.sv"                                                 -work error_adapter_0                                            -cdslib <<error_adapter_0>>                                           
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_router/altera_merlin_router_0005.sv"                                   -work router                                                     -cdslib <<router>>                                                    
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_multiplexer/altera_merlin_multiplexer_0004.sv"                         -work rsp_mux                                                    -cdslib <<rsp_mux>>                                                   
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_multiplexer/altera_merlin_arbitrator.sv"                               -work rsp_mux                                                    -cdslib <<rsp_mux>>                                                   
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_demultiplexer/altera_merlin_demultiplexer_0004.sv"                     -work rsp_demux                                                  -cdslib <<rsp_demux>>                                                 
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_multiplexer/altera_merlin_multiplexer_0003.sv"                         -work cmd_mux                                                    -cdslib <<cmd_mux>>                                                   
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_multiplexer/altera_merlin_arbitrator.sv"                               -work cmd_mux                                                    -cdslib <<cmd_mux>>                                                   
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_demultiplexer/altera_merlin_demultiplexer_0003.sv"                     -work cmd_demux                                                  -cdslib <<cmd_demux>>                                                 
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_router/altera_merlin_router_0004.sv"                                   -work router_001                                                 -cdslib <<router_001>>                                                
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_router/altera_merlin_router_0003.sv"                                   -work router                                                     -cdslib <<router>>                                                    
ncvlog     "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_st_adapter/altera_avalon_st_adapter_0001.v"                            -work avalon_st_adapter                                          -cdslib <<avalon_st_adapter>>                                         
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_st_handshake_clock_crosser/altera_avalon_st_handshake_clock_crosser.v" -work crosser                                                    -cdslib <<crosser>>                                                   
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_st_handshake_clock_crosser/altera_avalon_st_clock_crosser.v"           -work crosser                                                    -cdslib <<crosser>>                                                   
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_st_handshake_clock_crosser/altera_avalon_st_pipeline_base.v"           -work crosser                                                    -cdslib <<crosser>>                                                   
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_st_handshake_clock_crosser/altera_std_synchronizer_nocut.v"            -work crosser                                                    -cdslib <<crosser>>                                                   
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_multiplexer/altera_merlin_multiplexer_0002.sv"                         -work rsp_mux                                                    -cdslib <<rsp_mux>>                                                   
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_multiplexer/altera_merlin_arbitrator.sv"                               -work rsp_mux                                                    -cdslib <<rsp_mux>>                                                   
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_demultiplexer/altera_merlin_demultiplexer_0002.sv"                     -work rsp_demux                                                  -cdslib <<rsp_demux>>                                                 
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_multiplexer/altera_merlin_multiplexer_0001.sv"                         -work cmd_mux                                                    -cdslib <<cmd_mux>>                                                   
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_multiplexer/altera_merlin_arbitrator.sv"                               -work cmd_mux                                                    -cdslib <<cmd_mux>>                                                   
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_demultiplexer/altera_merlin_demultiplexer_0001.sv"                     -work cmd_demux                                                  -cdslib <<cmd_demux>>                                                 
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_traffic_limiter/altera_merlin_traffic_limiter.sv"                      -work merlin_master_translator_avalon_universal_master_0_limiter -cdslib <<merlin_master_translator_avalon_universal_master_0_limiter>>
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_traffic_limiter/altera_merlin_reorder_memory.sv"                       -work merlin_master_translator_avalon_universal_master_0_limiter -cdslib <<merlin_master_translator_avalon_universal_master_0_limiter>>
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_traffic_limiter/altera_avalon_sc_fifo.v"                               -work merlin_master_translator_avalon_universal_master_0_limiter -cdslib <<merlin_master_translator_avalon_universal_master_0_limiter>>
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_traffic_limiter/altera_avalon_st_pipeline_base.v"                      -work merlin_master_translator_avalon_universal_master_0_limiter -cdslib <<merlin_master_translator_avalon_universal_master_0_limiter>>
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_router/altera_merlin_router_0002.sv"                                   -work router_001                                                 -cdslib <<router_001>>                                                
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_router/altera_merlin_router_0001.sv"                                   -work router                                                     -cdslib <<router>>                                                    
ncvlog     "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_sc_fifo/altera_avalon_sc_fifo.v"                                       -work tx_bridge_s0_agent_rsp_fifo                                -cdslib <<tx_bridge_s0_agent_rsp_fifo>>                               
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_slave_agent/altera_merlin_slave_agent.sv"                              -work tx_bridge_s0_agent                                         -cdslib <<tx_bridge_s0_agent>>                                        
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_slave_agent/altera_merlin_burst_uncompressor.sv"                       -work tx_bridge_s0_agent                                         -cdslib <<tx_bridge_s0_agent>>                                        
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_master_agent/altera_merlin_master_agent.sv"                            -work merlin_master_translator_avalon_universal_master_0_agent   -cdslib <<merlin_master_translator_avalon_universal_master_0_agent>>  
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_slave_translator/altera_merlin_slave_translator.sv"                    -work tx_bridge_s0_translator                                    -cdslib <<tx_bridge_s0_translator>>                                   
ncvlog     "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_reset_controller/altera_reset_controller.v"                                   -work rst_controller                                             -cdslib <<rst_controller>>                                            
ncvlog     "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_reset_controller/altera_reset_synchronizer.v"                                 -work rst_controller                                             -cdslib <<rst_controller>>                                            
ncvlog     "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_mm_interconnect/altera_mm_interconnect_0003.v"                                -work mm_interconnect_2                                          -cdslib <<mm_interconnect_2>>                                         
ncvlog     "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_mm_interconnect/altera_mm_interconnect_0002.v"                                -work mm_interconnect_1                                          -cdslib <<mm_interconnect_1>>                                         
ncvlog     "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_mm_interconnect/altera_mm_interconnect_0001.v"                                -work mm_interconnect_0                                          -cdslib <<mm_interconnect_0>>                                         
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/timing_adapter/timing_adapter_0008.sv"                                               -work rxtx_timing_adapter_pauselen_tx                            -cdslib <<rxtx_timing_adapter_pauselen_tx>>                           
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/timing_adapter/timing_adapter_0007.sv"                                               -work rxtx_timing_adapter_pauselen_rx                            -cdslib <<rxtx_timing_adapter_pauselen_rx>>                           
ncvlog     "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_dc_fifo/altera_avalon_dc_fifo.v"                                       -work rxtx_dc_fifo_link_fault_status                             -cdslib <<rxtx_dc_fifo_link_fault_status>>                            
ncvlog     "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_dc_fifo/altera_dcfifo_synchronizer_bundle.v"                           -work rxtx_dc_fifo_link_fault_status                             -cdslib <<rxtx_dc_fifo_link_fault_status>>                            
ncvlog     "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_dc_fifo/altera_std_synchronizer_nocut.v"                               -work rxtx_dc_fifo_link_fault_status                             -cdslib <<rxtx_dc_fifo_link_fault_status>>                            
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/timing_adapter/timing_adapter_0006.sv"                                               -work txrx_timing_adapter_link_fault_status_export               -cdslib <<txrx_timing_adapter_link_fault_status_export>>              
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/timing_adapter/timing_adapter_0005.sv"                                               -work txrx_timing_adapter_link_fault_status_rx                   -cdslib <<txrx_timing_adapter_link_fault_status_rx>>                  
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/error_adapter/error_adapter_0002.sv"                                                 -work rx_st_error_adapter_stat                                   -cdslib <<rx_st_error_adapter_stat>>                                  
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_st_delay/altera_avalon_st_delay.sv"                                    -work rx_st_status_output_delay                                  -cdslib <<rx_st_status_output_delay>>                                 
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_eth_crc_pad_rem/altera_eth_crc_pad_rem_pipeline_stage.sv"                     -work rx_eth_crc_pad_rem                                         -cdslib <<rx_eth_crc_pad_rem>>                                        
ncvlog     "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_eth_crc_pad_rem/altera_eth_crc_pad_rem_pipeline_base.v"                       -work rx_eth_crc_pad_rem                                         -cdslib <<rx_eth_crc_pad_rem>>                                        
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/timing_adapter/timing_adapter_0004.sv"                                               -work rx_timing_adapter_frame_status_out_frame_decoder           -cdslib <<rx_timing_adapter_frame_status_out_frame_decoder>>          
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_eth_frame_decoder/altera_eth_frame_decoder_pipeline_stage.sv"                 -work rx_eth_frame_decoder                                       -cdslib <<rx_eth_frame_decoder>>                                      
ncvlog     "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_eth_frame_decoder/altera_eth_frame_decoder_pipeline_base.v"                   -work rx_eth_frame_decoder                                       -cdslib <<rx_eth_frame_decoder>>                                      
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/timing_adapter/timing_adapter_0003.sv"                                               -work rx_st_timing_adapter_frame_status_in                       -cdslib <<rx_st_timing_adapter_frame_status_in>>                      
ncvlog     "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_eth_10g_rx_register_map/altera_avalon_st_clock_crosser.v"                     -work rx_register_map                                            -cdslib <<rx_register_map>>                                           
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/timing_adapter/timing_adapter_0002.sv"                                               -work tx_st_timing_adapter_splitter_out_0                        -cdslib <<tx_st_timing_adapter_splitter_out_0>>                       
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_st_splitter/altera_avalon_st_splitter.sv"                              -work tx_st_splitter_xgmii                                       -cdslib <<tx_st_splitter_xgmii>>                                      
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/timing_adapter/timing_adapter_0001.sv"                                               -work tx_st_timing_adapter_splitter_in                           -cdslib <<tx_st_timing_adapter_splitter_in>>                          
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_st_pipeline_stage/altera_avalon_st_pipeline_stage.sv"                  -work tx_st_pipeline_stage_rs                                    -cdslib <<tx_st_pipeline_stage_rs>>                                   
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_st_pipeline_stage/altera_avalon_st_pipeline_base.v"                    -work tx_st_pipeline_stage_rs                                    -cdslib <<tx_st_pipeline_stage_rs>>                                   
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/multiplexer/multiplexer_0001.sv"                                                     -work tx_st_mux_flow_control_user_frame                          -cdslib <<tx_st_mux_flow_control_user_frame>>                         
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/error_adapter/error_adapter_0001.sv"                                                 -work tx_st_pause_ctrl_error_adapter                             -cdslib <<tx_st_pause_ctrl_error_adapter>>                            
ncvlog     "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_eth_10g_tx_register_map/altera_avalon_st_clock_crosser.v"                     -work tx_register_map                                            -cdslib <<tx_register_map>>                                           
ncvlog     "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_avalon_mm_bridge/altera_avalon_mm_bridge.v"                                   -work tx_bridge                                                  -cdslib <<tx_bridge>>                                                 
ncvlog -sv "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/altera_merlin_master_translator/altera_merlin_master_translator.sv"                  -work merlin_master_translator                                   -cdslib <<merlin_master_translator>>                                  
ncvlog     "C:/Users/DELL/Desktop/Ethernet/Ethernet_10g/ipcore/Eth_10gmac/Eth_10gmac_sim/Eth_10gmac.v"                                                                                                                                                                                                               
